##### Author: Jimin Kim (jk55@uw.edu)
##### Version 1.5.0

# Lab 5 Report

## Group Members:

In [6]:
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

%matplotlib inline
import dynworm as dw

## Exercise 1: Visualize brain connectomes

<img src="lab5_exercise1.png" width="1000">

In [11]:
# Load synaptic connectome and neuron classes

celegans_syn_conn_pd = pd.read_excel('connectome_syn.xlsx')
celegans_syn_conn_np = np.array(celegans_syn_conn_pd)

# Classes are ordered according to the neurons' order in synaptic connectome
neuron_classes = np.load('neuron_classes.npy') 

In [12]:
# Adjacency matrix of the first 10 neurons
print(celegans_syn_conn_np[:10, :10])

[[0 0 0 3 0 0 7 0 0 0]
 [0 0 1 0 7 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 2 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [15]:
# Neuron classes of the first 10 neurons
print(neuron_classes[:100])

['sensory' 'sensory' 'sensory' 'sensory' 'sensory' 'sensory' 'sensory'
 'sensory' 'sensory' 'sensory' 'sensory' 'sensory' 'sensory' 'sensory'
 'inter' 'sensory' 'inter' 'sensory' 'sensory' 'sensory' 'sensory'
 'sensory' 'sensory' 'motor' 'inter' 'sensory' 'sensory' 'inter' 'motor'
 'sensory' 'sensory' 'sensory' 'sensory' 'sensory' 'motor' 'sensory'
 'motor' 'sensory' 'motor' 'sensory' 'motor' 'inter' 'motor' 'sensory'
 'inter' 'motor' 'sensory' 'inter' 'inter' 'sensory' 'inter' 'motor'
 'sensory' 'motor' 'sensory' 'inter' 'inter' 'sensory' 'inter' 'sensory'
 'sensory' 'motor' 'sensory' 'inter' 'inter' 'sensory' 'inter' 'motor'
 'sensory' 'sensory' 'sensory' 'inter' 'sensory' 'sensory' 'sensory'
 'sensory' 'sensory' 'inter' 'sensory' 'inter' 'sensory' 'sensory'
 'sensory' 'inter' 'motor' 'motor' 'inter' 'motor' 'motor' 'sensory'
 'inter' 'inter' 'motor' 'inter' 'inter' 'motor' 'inter' 'inter' 'sensory'
 'inter']


In [16]:
def vis_conn(syn_conn, neuron_classes):
    
    # YOUR CODE HERE
    # The function should output a 1 x 3 subplot
    # For each subplot, make sure to set plt.ylim(len(sub_adjacency_matrix), 0) so that first row starts with neuron 0
    # Add appropriate x,y labels for each subplot (e.g. sensory vs sensory, inter vs inter, etc)
    
    sensor_mask_arr = []
    inter_mask_arr = []
    motor_mask_arr = []
    
    dimension = len(syn_conn)

    # Generating boolean integer masks for the three types of neuron.
    for i in range(len(neuron_classes)):
        sensor_mask_arr.append(int(neuron_classes[i] == 'sensory'))
        inter_mask_arr.append(int(neuron_classes[i] == 'inter'))
        motor_mask_arr.append(int(neuron_classes[i] == 'motor'))
    
    # sensor_mask
    # sensor_plot = syn_conn[:, sensor_mask][sensor_mask, :]
    # 
    sensor_arr = np.zeros((dimension, dimension))
    inter_arr = np.zeros((dimension, dimension))
    motor_arr = np.zeros((dimension, dimension))
    
    for i in range(len(neuron_classes)):
        for j in range(len(neuron_classes)):
            if sensor_mask_arr[i] and sensor_mask_arr[j]:
                sen_arr[i][j] = syn_conn[i][j]
            elif inter_mask_arr[i] and inter_mask_arr[j]:
                inter_arr[i][j] = syn_conn[i][j]
            elif motor_mask_arr[i] and motor_mask_arr[j]:
                motor_arr[i][j] = syn_conn[i][j]
            else:
                sensor_arr[i][j] = 0
                inter_arr[i][j] = 0
                motor_arr[i][j] = 0
            
    fig, (sen, int, mot) = plt.subplots(1,3)
    plt.figure(figsize=(10,10))
    plt.pcolor(directed_adj_mat, cmap = 'Greys', vmin = 0, vmax = 1)
    plt.ylim(len(directed_adj_mat), 0)
    plt.xticks(fontsize=40)
    plt.yticks(fontsize=40)
    plt.show()
    
    
    

SyntaxError: invalid syntax (21383857.py, line 27)

In [ ]:
# Test your function here

vis_conn(celegans_syn_conn_np, neuron_classes)

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, False, True, True, True, True, True, True, False, False, True, True, False, False, True, True, True, True, True, False, True, False, True, False, True, False, False, False, True, False, False, True, False, False, True, False, False, True, False, True, False, False, True, False, True, True, False, True, False, False, True, False, False, True, True, True, False, True, True, True, True, True, False, True, False, True, True, True, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, False, False, True, False, True, False, True

NameError: name 'directed_adj_mat' is not defined

<Figure size 720x720 with 0 Axes>

## Exercise 2: Locating the most connected vertices

<img src="lab5_exercise2.png" width="1000">

In [ ]:
# Load the synaptic connectome and sample social network

syn_conn_pd = pd.read_excel('connectome_syn.xlsx')
syn_conn_np = np.array(syn_conn_pd)

social_network_sample_pd = pd.read_excel('social_network_sample.xlsx')
social_network_sample_np = np.array(social_network_sample_pd)

In [ ]:
def find_hub_vertices(adj_mat, num_vertices):
    
    # YOUR CODE HERE
    
    return indegree_list, outdegree_list

In [ ]:
# Test your function with synaptic connectome

indegree_list_syn_conn, outdegree_list_syn_conn = find_hub_vertices(adj_mat = syn_conn_np, num_vertices = 10)

In [ ]:
print(indegree_list_syn_conn)

In [ ]:
print(outdegree_list_syn_conn)

In [ ]:
# Test your function with sample social media network

indegree_list_SN, outdegree_list_SN = find_hub_vertices(adj_mat = social_network_sample_np, num_vertices = 5)

In [ ]:
print(indegree_list_SN)

In [ ]:
print(outdegree_list_SN)

## Exercise 3: Removing vertices from a graph

<img src="lab5_exercise3.png" width="1000">

In [ ]:
# We will use the pre-existing directed graph sample earlier in the lab

directed_adj_mat_pd = pd.read_excel('directed_sample.xlsx')
directed_adj_mat_np = np.array(directed_adj_mat_pd)

In [ ]:
def remove_vertices(adj_mat, vertices_2b_removed):
    
    # YOUR CODE HERE
    
    return adj_mat_new

In [ ]:
vertices_2b_removed_1 = [0, 5]        # Vertices to be removed set 1
vertices_2b_removed_2 = [1, 2, 6]     # Vertices to be removed set 2

In [ ]:
# Test your function with set 1

directed_adj_mat_new_1 = remove_vertices(adj_mat = directed_adj_mat_np, vertices_2b_removed = vertices_2b_removed_1)

In [ ]:
# Test your function with set 2

directed_adj_mat_new_2 = remove_vertices(adj_mat = directed_adj_mat_np, vertices_2b_removed = vertices_2b_removed_2)

### Original graph image for reference

<img src="directed_sample_graph.png" width="400">

In [ ]:
# Using networkX, plot your directed graph with removed vertices according to vertices_2b_removed_1
# Use circular graph layout
# Label your edges according to their weights

# YOUR CODE HERE

In [ ]:
# Using networkX, plot your directed graph with removed vertices according to vertices_2b_removed_2
# Use circular graph layout
# Label your edges according to their weights

# YOUR CODE HERE

## Exercise 4: Adding a new vertex to a graph

<img src="lab5_exercise4.png" width="1000">

In [ ]:
# We will use the pre-existing directed graph sample earlier in the lab
# The graph has 7 vertices

directed_adj_mat_pd = pd.read_excel('directed_sample.xlsx')
directed_adj_mat_np = np.array(directed_adj_mat_pd)

In [ ]:
def add_vertex(adj_mat, outgoing_edges, incoming_edges):
    
    # YOUR CODE HERE
    # The original directed graph has 7 vertices
    # The new vertex to be added can be regarded as 8th vertex of the graph
    # You can assume that each edge being added has weight of 1
    
    return adj_mat_new

In [ ]:
# Define outgoing and incoming edges for the new vertex to be added

outgoing_edges = [2, 3, 5]
incoming_edges = [3, 4, 6]

In [ ]:
# Test your function with provided list of outgoing/incoming edges

directed_adj_mat_vertex_added = add_vertex(adj_mat = directed_adj_mat_np, 
                                  outgoing_edges = outgoing_edges, 
                                  incoming_edges = incoming_edges)

### Original graph image for reference

<img src="directed_sample_graph.png" width="400">

In [ ]:
# Using networkX, plot your directed graph with added vertices according to outgoing_edges and incoming_edges
# Use circular graph layout
# Label your edges according to their weights

# YOUR CODE HERE

## Exercise 5: Re-wire neurons to restore behavior of C. elegans

<img src="lab5_exercise5.png" width="1000">

### Note: If you wish to use the included C. elegans simulation code in lab template folder outside of EE 241 (e.g. research purpose), please cite the following paper 
### Kim, J., Leahy, W., & Shlizerman, E. (2019). Neural interactome: Interactive simulation of a neuronal system. Frontiers in Computational Neuroscience, 13, 8. 

In [ ]:
# Load synaptic connectome and neuron classes

damaged_syn_conn_pd = pd.read_excel('connectome_syn.xlsx')
damaged_syn_conn_np = np.array(damaged_syn_conn_pd)

## Motorneurons' activities during gentle tail touch (Damaged brain)

<img src="damaged_AVA_motor_activities.png" width="450">

## Simulated body movement during gentle tail touch (Damaged brain)

In [ ]:
from ipywidgets import Video

Video.from_file("escape_response_damaged.mp4", width=500, height=500)

In [ ]:
# Re-wiring instructions for AVAL and AVAR neurons

outgoing_AVAL_triples = np.load('AVAL_outgoing_triples.npy') # AVAL is the 47th vertex in the graph
incoming_AVAL_triples = np.load('AVAL_incoming_triples.npy') # AVAL is the 47th vertex in the graph

outgoing_AVAR_triples = np.load('AVAR_outgoing_triples.npy') # AVAR is the 55th vertex in the graph
incoming_AVAR_triples = np.load('AVAR_incoming_triples.npy') # AVAR is the 55th vertex in the graph

# Each row in the triple is ordered as [Source neuron index, Target neuron index, Synaptic weight]

rewiring_triples_AVAL = [outgoing_AVAL_triples, incoming_AVAL_triples]
rewiring_triples_AVAR = [outgoing_AVAR_triples, incoming_AVAR_triples]

In [ ]:
def rewire_neurons(damaged_synaptic_adj_matrix, rewiring_instructions_AVAL, rewiring_instructions_AVAR):
    
    # YOUR CODE HERE
    # AVAL, AVAR neurons take the indices of 47, 55 respectively in the damaged_syn_conn_np   
    
    return repaired_synaptic_adj_matrix

In [ ]:
repaired_synaptic_adj_matrix = rewire_neurons(damaged_synaptic_adj_matrix = damaged_syn_conn_np, 
                                              rewiring_instructions_AVAL = rewiring_triples_AVAL, 
                                              rewiring_instructions_AVAR = rewiring_triples_AVAR)

In [ ]:
# Test your repaired connectome 

dw.network_sim.test_brain_repair(repaired_synaptic_adj_matrix) 

# If successfully repaired, function will output 
# 1) Motorneurons activity 
# 2) Simulated body movement video with repaired brain